<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.5; }
        .header { margin-bottom: 25px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; color: #0f172a; margin: 0; }
        .meta { font-size: 10px; color: #666; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f1f5f9; text-align: left; font-weight: bold; padding: 6px; border: 1px solid #cbd5e1; }
        td { padding: 6px; border: 1px solid #cbd5e1; }
        .row-alt { background-color: #f8fafc; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report_title }}</div>
        <div class="meta">
            Generated At: {{ $generated_at }} | Generated By: {{ $generated_by }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Bug Title</th>
                <th>Project</th>
                <th>Priority</th>
                <th>Reporter</th>
                <th>Assigned Developer</th>
                <th>Related Fix Task</th>
                <th>Resolution Status</th>
                <th>Actual Hours</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bugs as $index => $bug)
                <tr class="{{ $index % 2 === 0 ? '' : 'row-alt' }}">
                    <td>
                        <strong>{{ $bug->title }}</strong>
                        <div style="font-size: 9px; color: #666; margin-top: 2px;">{{ Str::limit($bug->description, 80) }}</div>
                    </td>
                    <td>{{ $bug->project->name }}</td>
                    <td>{{ $bug->priority }}</td>
                    <td>{{ $bug->client->name ?? 'N/A' }}</td>
                    <td>{{ $bug->developer->name ?? 'Unassigned' }}</td>
                    <td>{{ $bug->task->name ?? '-' }}</td>
                    <td>{{ $bug->status }}</td>
                    <td>{{ number_format($bug->actual_hours, 1) }} hrs</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No bugs matching the criteria were found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
