<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.5; }
        .header { margin-bottom: 25px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; color: #0f172a; margin: 0; }
        .meta { font-size: 10px; color: #666; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f1f5f9; text-align: left; font-weight: bold; padding: 6px; border: 1px solid #cbd5e1; }
        td { padding: 6px; border: 1px solid #cbd5e1; }
        .row-alt { background-color: #f8fafc; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report_title }}</div>
        <div class="meta">
            Generated At: {{ $generated_at }} | Generated By: {{ $generated_by }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Developer Name</th>
                <th>Completed Tasks</th>
                <th>Est Hours (Done Tasks)</th>
                <th>Act Hours (Done Tasks)</th>
                <th>Time Variance</th>
                <th>Productivity Score</th>
            </tr>
        </thead>
        <tbody>
            @forelse($developers as $index => $dev)
                <tr class="{{ $index % 2 === 0 ? '' : 'row-alt' }}">
                    <td><strong>{{ $dev->name }}</strong></td>
                    <td>{{ $dev->completed_tasks_count }} Tasks</td>
                    <td>{{ number_format($dev->estimated_hours, 1) }}</td>
                    <td>{{ number_format($dev->actual_hours, 1) }}</td>
                    <td>{{ number_format($dev->variance, 1) }}</td>
                    <td><strong>{{ $dev->productivity }}%</strong></td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No developers found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
