<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.5; }
        .header { margin-bottom: 25px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; color: #0f172a; margin: 0; }
        .meta { font-size: 10px; color: #666; margin-top: 5px; }
        .project-section { margin-top: 20px; }
        .project-title { font-size: 13px; font-weight: bold; color: #4f46e5; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f1f5f9; text-align: left; font-weight: bold; padding: 6px; border: 1px solid #cbd5e1; }
        td { padding: 6px; border: 1px solid #cbd5e1; }
        .row-alt { background-color: #f8fafc; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report_title }}</div>
        <div class="meta">
            Generated At: {{ $generated_at }} | Generated By: {{ $generated_by }}
        </div>
    </div>

    @forelse($projects as $project)
        <div class="project-section">
            <div class="project-title">{{ $project->name }}</div>
            <table>
                <thead>
                    <tr>
                        <th width="30%">Milestone Name</th>
                        <th width="20%">Status</th>
                        <th width="20%">Deadline</th>
                        <th width="15%">Tasks (Done/Total)</th>
                        <th width="15%">Average Progress (%)</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($project->milestones as $index => $m)
                        <tr class="{{ $index % 2 === 0 ? '' : 'row-alt' }}">
                            <td><strong>{{ $m->name }}</strong></td>
                            <td>{{ $m->status }}</td>
                            <td>{{ $m->deadline->format('Y-m-d') }}</td>
                            <td>{{ $m->completed_tasks }} / {{ $m->total_tasks }}</td>
                            <td><strong>{{ number_format($m->average_progress, 1) }}%</strong></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" style="text-align: center; color: #666;">No milestones configured for this project.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    @empty
        <p>No projects found.</p>
    @endforelse
</body>
</html>
