<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.5; }
        .header { margin-bottom: 25px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; color: #0f172a; margin: 0; }
        .meta { font-size: 10px; color: #666; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f1f5f9; text-align: left; font-weight: bold; padding: 6px; border: 1px solid #cbd5e1; }
        td { padding: 6px; border: 1px solid #cbd5e1; }
        .row-alt { background-color: #f8fafc; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report_title }}</div>
        <div class="meta">
            Generated At: {{ $generated_at }} | Generated By: {{ $generated_by }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Status</th>
                <th>Milestones (Completed/Total)</th>
                <th>Total Tasks</th>
                <th>Average Progress (%)</th>
                <th>Est Hours</th>
                <th>Act Hours</th>
                <th>Variance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($projects as $index => $project)
                <tr class="{{ $index % 2 === 0 ? '' : 'row-alt' }}">
                    <td><strong>{{ $project->name }}</strong></td>
                    <td>{{ $project->status }}</td>
                    <td>{{ $project->completed_milestones }} / {{ $project->total_milestones }}</td>
                    <td>{{ $project->total_tasks }}</td>
                    <td><strong>{{ number_format($project->average_progress, 1) }}%</strong></td>
                    <td>{{ number_format($project->estimated_hours, 1) }}</td>
                    <td>{{ number_format($project->actual_hours, 1) }}</td>
                    <td>{{ number_format($project->actual_hours - $project->estimated_hours, 1) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No projects found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
