@php
    $logoPath = public_path('images/logo.png');
    $logoBase64 = '';
    if (file_exists($logoPath)) {
        $logoBase64 = 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath));
    }
@endphp

<div class="company-letterhead" style="text-align: center; border-bottom: 3px double #0f172a; padding-bottom: 12px; margin-bottom: 25px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
    @if($logoBase64)
        <div style="margin-bottom: 8px;">
            <img src="{{ $logoBase64 }}" style="height: 65px; display: inline-block;">
        </div>
    @endif
    <div style="font-size: 20px; font-weight: bold; text-transform: uppercase; color: #0f172a; margin: 0; line-height: 1.2; letter-spacing: 0.5px;">CV. MAHKOTA BARITO</div>
    <div style="font-size: 11px; color: #334155; margin-top: 4px; line-height: 1.5; font-weight: normal;">
        Jl Temanggung Silam RT 002/RW 004 NO 29<br>
        Puruk Cahu, Kec. Murung, Kabupaten Murung Raya, Kalimantan Tengah 73911
    </div>
    <div style="font-size: 13px; font-weight: bold; color: #4f46e5; margin-top: 6px; letter-spacing: 2px; text-transform: uppercase;">CODEVISION</div>
</div>

<div class="report-meta-header" style="margin-bottom: 20px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">
    <div style="font-size: 16px; font-weight: bold; color: #0f172a; text-transform: uppercase; margin: 0;">{{ $report_title }}</div>
    <div style="font-size: 10px; color: #64748b; margin-top: 5px; font-weight: 500;">
        Generated At: <span style="color: #334155;">{{ $generated_at }}</span> &nbsp;|&nbsp; 
        Generated By: <span style="color: #334155;">{{ $generated_by }}</span>
        @if(isset($start_date) && isset($end_date))
            &nbsp;|&nbsp; Period: <span style="color: #4f46e5; font-weight: bold;">{{ $start_date }}</span> to <span style="color: #4f46e5; font-weight: bold;">{{ $end_date }}</span>
        @elseif(isset($start_date))
            &nbsp;|&nbsp; Period: From <span style="color: #4f46e5; font-weight: bold;">{{ $start_date }}</span>
        @elseif(isset($end_date))
            &nbsp;|&nbsp; Period: Until <span style="color: #4f46e5; font-weight: bold;">{{ $end_date }}</span>
        @endif
    </div>
</div>
